// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYz1g3259DZV9TbyJ-cBz-Vil5oQGNJJ4',
    appId: '1:361650427365:web:581864889cae2c97f08b0c',
    messagingSenderId: '361650427365',
    projectId: 'whats-app-36cff',
    authDomain: 'whats-app-36cff.firebaseapp.com',
    storageBucket: 'whats-app-36cff.appspot.com',
    measurementId: 'G-002MTW6WJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9leWKxCzsT9krPsLFjnlFc3UinEpIVI8',
    appId: '1:361650427365:android:4def40cd447f4aaef08b0c',
    messagingSenderId: '361650427365',
    projectId: 'whats-app-36cff',
    storageBucket: 'whats-app-36cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgq91xdSbaB_iic-8DJQIirzLNU5sE5pI',
    appId: '1:361650427365:ios:4d04b4896fdaad3ff08b0c',
    messagingSenderId: '361650427365',
    projectId: 'whats-app-36cff',
    storageBucket: 'whats-app-36cff.appspot.com',
    iosClientId: '361650427365-381t5qcqk2v414epfu33gm4bf561ls60.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgq91xdSbaB_iic-8DJQIirzLNU5sE5pI',
    appId: '1:361650427365:ios:4d04b4896fdaad3ff08b0c',
    messagingSenderId: '361650427365',
    projectId: 'whats-app-36cff',
    storageBucket: 'whats-app-36cff.appspot.com',
    iosClientId: '361650427365-381t5qcqk2v414epfu33gm4bf561ls60.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYz1g3259DZV9TbyJ-cBz-Vil5oQGNJJ4',
    appId: '1:361650427365:web:f3640ffd5cf1b668f08b0c',
    messagingSenderId: '361650427365',
    projectId: 'whats-app-36cff',
    authDomain: 'whats-app-36cff.firebaseapp.com',
    storageBucket: 'whats-app-36cff.appspot.com',
    measurementId: 'G-2817D38CBN',
  );

}